# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/home/bojan/Documents/projects/mugo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/home/bojan/Documents/projects/mugo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/home/bojan/Documents/projects/mugo/CMakeFiles /usr/home/bojan/Documents/projects/mugo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/home/bojan/Documents/projects/mugo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named os.elf

# Build rule for target.
os.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 os.elf
.PHONY : os.elf

# fast build rule for target.
os.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/build
.PHONY : os.elf/fast

#=============================================================================
# Target rules for targets named mman.elf

# Build rule for target.
mman.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mman.elf
.PHONY : mman.elf

# fast build rule for target.
mman.elf/fast:
	$(MAKE) $(MAKESILENT) -f serv/mman/CMakeFiles/mman.elf.dir/build.make serv/mman/CMakeFiles/mman.elf.dir/build
.PHONY : mman.elf/fast

arch/i686/boot/boot.o: arch/i686/boot/boot.asm.o

.PHONY : arch/i686/boot/boot.o

# target to build an object file
arch/i686/boot/boot.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/boot.asm.o
.PHONY : arch/i686/boot/boot.asm.o

arch/i686/boot/gdt.o: arch/i686/boot/gdt.c.o

.PHONY : arch/i686/boot/gdt.o

# target to build an object file
arch/i686/boot/gdt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/gdt.c.o
.PHONY : arch/i686/boot/gdt.c.o

arch/i686/boot/gdt.i: arch/i686/boot/gdt.c.i

.PHONY : arch/i686/boot/gdt.i

# target to preprocess a source file
arch/i686/boot/gdt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/gdt.c.i
.PHONY : arch/i686/boot/gdt.c.i

arch/i686/boot/gdt.s: arch/i686/boot/gdt.c.s

.PHONY : arch/i686/boot/gdt.s

# target to generate assembly for a file
arch/i686/boot/gdt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/gdt.c.s
.PHONY : arch/i686/boot/gdt.c.s

arch/i686/boot/interrupt.o: arch/i686/boot/interrupt.asm.o

.PHONY : arch/i686/boot/interrupt.o

# target to build an object file
arch/i686/boot/interrupt.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/interrupt.asm.o
.PHONY : arch/i686/boot/interrupt.asm.o

arch/i686/boot/load_tables.o: arch/i686/boot/load_tables.asm.o

.PHONY : arch/i686/boot/load_tables.o

# target to build an object file
arch/i686/boot/load_tables.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/load_tables.asm.o
.PHONY : arch/i686/boot/load_tables.asm.o

arch/i686/boot/multiboot.o: arch/i686/boot/multiboot.asm.o

.PHONY : arch/i686/boot/multiboot.o

# target to build an object file
arch/i686/boot/multiboot.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/boot/multiboot.asm.o
.PHONY : arch/i686/boot/multiboot.asm.o

arch/i686/drivers/pic.o: arch/i686/drivers/pic.c.o

.PHONY : arch/i686/drivers/pic.o

# target to build an object file
arch/i686/drivers/pic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/pic.c.o
.PHONY : arch/i686/drivers/pic.c.o

arch/i686/drivers/pic.i: arch/i686/drivers/pic.c.i

.PHONY : arch/i686/drivers/pic.i

# target to preprocess a source file
arch/i686/drivers/pic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/pic.c.i
.PHONY : arch/i686/drivers/pic.c.i

arch/i686/drivers/pic.s: arch/i686/drivers/pic.c.s

.PHONY : arch/i686/drivers/pic.s

# target to generate assembly for a file
arch/i686/drivers/pic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/pic.c.s
.PHONY : arch/i686/drivers/pic.c.s

arch/i686/drivers/timer.o: arch/i686/drivers/timer.c.o

.PHONY : arch/i686/drivers/timer.o

# target to build an object file
arch/i686/drivers/timer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/timer.c.o
.PHONY : arch/i686/drivers/timer.c.o

arch/i686/drivers/timer.i: arch/i686/drivers/timer.c.i

.PHONY : arch/i686/drivers/timer.i

# target to preprocess a source file
arch/i686/drivers/timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/timer.c.i
.PHONY : arch/i686/drivers/timer.c.i

arch/i686/drivers/timer.s: arch/i686/drivers/timer.c.s

.PHONY : arch/i686/drivers/timer.s

# target to generate assembly for a file
arch/i686/drivers/timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/timer.c.s
.PHONY : arch/i686/drivers/timer.c.s

arch/i686/drivers/vga.o: arch/i686/drivers/vga.c.o

.PHONY : arch/i686/drivers/vga.o

# target to build an object file
arch/i686/drivers/vga.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/vga.c.o
.PHONY : arch/i686/drivers/vga.c.o

arch/i686/drivers/vga.i: arch/i686/drivers/vga.c.i

.PHONY : arch/i686/drivers/vga.i

# target to preprocess a source file
arch/i686/drivers/vga.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/vga.c.i
.PHONY : arch/i686/drivers/vga.c.i

arch/i686/drivers/vga.s: arch/i686/drivers/vga.c.s

.PHONY : arch/i686/drivers/vga.s

# target to generate assembly for a file
arch/i686/drivers/vga.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/drivers/vga.c.s
.PHONY : arch/i686/drivers/vga.c.s

arch/i686/early.o: arch/i686/early.c.o

.PHONY : arch/i686/early.o

# target to build an object file
arch/i686/early.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/early.c.o
.PHONY : arch/i686/early.c.o

arch/i686/early.i: arch/i686/early.c.i

.PHONY : arch/i686/early.i

# target to preprocess a source file
arch/i686/early.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/early.c.i
.PHONY : arch/i686/early.c.i

arch/i686/early.s: arch/i686/early.c.s

.PHONY : arch/i686/early.s

# target to generate assembly for a file
arch/i686/early.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/early.c.s
.PHONY : arch/i686/early.c.s

arch/i686/idt.o: arch/i686/idt.c.o

.PHONY : arch/i686/idt.o

# target to build an object file
arch/i686/idt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/idt.c.o
.PHONY : arch/i686/idt.c.o

arch/i686/idt.i: arch/i686/idt.c.i

.PHONY : arch/i686/idt.i

# target to preprocess a source file
arch/i686/idt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/idt.c.i
.PHONY : arch/i686/idt.c.i

arch/i686/idt.s: arch/i686/idt.c.s

.PHONY : arch/i686/idt.s

# target to generate assembly for a file
arch/i686/idt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/idt.c.s
.PHONY : arch/i686/idt.c.s

arch/i686/init.o: arch/i686/init.c.o

.PHONY : arch/i686/init.o

# target to build an object file
arch/i686/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/init.c.o
.PHONY : arch/i686/init.c.o

arch/i686/init.i: arch/i686/init.c.i

.PHONY : arch/i686/init.i

# target to preprocess a source file
arch/i686/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/init.c.i
.PHONY : arch/i686/init.c.i

arch/i686/init.s: arch/i686/init.c.s

.PHONY : arch/i686/init.s

# target to generate assembly for a file
arch/i686/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/init.c.s
.PHONY : arch/i686/init.c.s

arch/i686/interrupt.o: arch/i686/interrupt.c.o

.PHONY : arch/i686/interrupt.o

# target to build an object file
arch/i686/interrupt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/interrupt.c.o
.PHONY : arch/i686/interrupt.c.o

arch/i686/interrupt.i: arch/i686/interrupt.c.i

.PHONY : arch/i686/interrupt.i

# target to preprocess a source file
arch/i686/interrupt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/interrupt.c.i
.PHONY : arch/i686/interrupt.c.i

arch/i686/interrupt.s: arch/i686/interrupt.c.s

.PHONY : arch/i686/interrupt.s

# target to generate assembly for a file
arch/i686/interrupt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/interrupt.c.s
.PHONY : arch/i686/interrupt.c.s

arch/i686/panic.o: arch/i686/panic.c.o

.PHONY : arch/i686/panic.o

# target to build an object file
arch/i686/panic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/panic.c.o
.PHONY : arch/i686/panic.c.o

arch/i686/panic.i: arch/i686/panic.c.i

.PHONY : arch/i686/panic.i

# target to preprocess a source file
arch/i686/panic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/panic.c.i
.PHONY : arch/i686/panic.c.i

arch/i686/panic.s: arch/i686/panic.c.s

.PHONY : arch/i686/panic.s

# target to generate assembly for a file
arch/i686/panic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/panic.c.s
.PHONY : arch/i686/panic.c.s

arch/i686/sysenter.o: arch/i686/sysenter.asm.o

.PHONY : arch/i686/sysenter.o

# target to build an object file
arch/i686/sysenter.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/sysenter.asm.o
.PHONY : arch/i686/sysenter.asm.o

arch/i686/thread.o: arch/i686/thread.c.o

.PHONY : arch/i686/thread.o

# target to build an object file
arch/i686/thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/thread.c.o
.PHONY : arch/i686/thread.c.o

arch/i686/thread.i: arch/i686/thread.c.i

.PHONY : arch/i686/thread.i

# target to preprocess a source file
arch/i686/thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/thread.c.i
.PHONY : arch/i686/thread.c.i

arch/i686/thread.s: arch/i686/thread.c.s

.PHONY : arch/i686/thread.s

# target to generate assembly for a file
arch/i686/thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/thread.c.s
.PHONY : arch/i686/thread.c.s

arch/i686/thread_asm.o: arch/i686/thread_asm.asm.o

.PHONY : arch/i686/thread_asm.o

# target to build an object file
arch/i686/thread_asm.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/thread_asm.asm.o
.PHONY : arch/i686/thread_asm.asm.o

arch/i686/trace.o: arch/i686/trace.asm.o

.PHONY : arch/i686/trace.o

# target to build an object file
arch/i686/trace.asm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/trace.asm.o
.PHONY : arch/i686/trace.asm.o

arch/i686/util.o: arch/i686/util.c.o

.PHONY : arch/i686/util.o

# target to build an object file
arch/i686/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/util.c.o
.PHONY : arch/i686/util.c.o

arch/i686/util.i: arch/i686/util.c.i

.PHONY : arch/i686/util.i

# target to preprocess a source file
arch/i686/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/util.c.i
.PHONY : arch/i686/util.c.i

arch/i686/util.s: arch/i686/util.c.s

.PHONY : arch/i686/util.s

# target to generate assembly for a file
arch/i686/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/arch/i686/util.c.s
.PHONY : arch/i686/util.c.s

kern/kmalloc.o: kern/kmalloc.c.o

.PHONY : kern/kmalloc.o

# target to build an object file
kern/kmalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kmalloc.c.o
.PHONY : kern/kmalloc.c.o

kern/kmalloc.i: kern/kmalloc.c.i

.PHONY : kern/kmalloc.i

# target to preprocess a source file
kern/kmalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kmalloc.c.i
.PHONY : kern/kmalloc.c.i

kern/kmalloc.s: kern/kmalloc.c.s

.PHONY : kern/kmalloc.s

# target to generate assembly for a file
kern/kmalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kmalloc.c.s
.PHONY : kern/kmalloc.c.s

kern/kmem.o: kern/kmem.c.o

.PHONY : kern/kmem.o

# target to build an object file
kern/kmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kmem.c.o
.PHONY : kern/kmem.c.o

kern/kmem.i: kern/kmem.c.i

.PHONY : kern/kmem.i

# target to preprocess a source file
kern/kmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kmem.c.i
.PHONY : kern/kmem.c.i

kern/kmem.s: kern/kmem.c.s

.PHONY : kern/kmem.s

# target to generate assembly for a file
kern/kmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kmem.c.s
.PHONY : kern/kmem.c.s

kern/kprint.o: kern/kprint.c.o

.PHONY : kern/kprint.o

# target to build an object file
kern/kprint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kprint.c.o
.PHONY : kern/kprint.c.o

kern/kprint.i: kern/kprint.c.i

.PHONY : kern/kprint.i

# target to preprocess a source file
kern/kprint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kprint.c.i
.PHONY : kern/kprint.c.i

kern/kprint.s: kern/kprint.c.s

.PHONY : kern/kprint.s

# target to generate assembly for a file
kern/kprint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/kprint.c.s
.PHONY : kern/kprint.c.s

kern/main.o: kern/main.c.o

.PHONY : kern/main.o

# target to build an object file
kern/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/main.c.o
.PHONY : kern/main.c.o

kern/main.i: kern/main.c.i

.PHONY : kern/main.i

# target to preprocess a source file
kern/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/main.c.i
.PHONY : kern/main.c.i

kern/main.s: kern/main.c.s

.PHONY : kern/main.s

# target to generate assembly for a file
kern/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/main.c.s
.PHONY : kern/main.c.s

kern/panic.o: kern/panic.c.o

.PHONY : kern/panic.o

# target to build an object file
kern/panic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/panic.c.o
.PHONY : kern/panic.c.o

kern/panic.i: kern/panic.c.i

.PHONY : kern/panic.i

# target to preprocess a source file
kern/panic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/panic.c.i
.PHONY : kern/panic.c.i

kern/panic.s: kern/panic.c.s

.PHONY : kern/panic.s

# target to generate assembly for a file
kern/panic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/panic.c.s
.PHONY : kern/panic.c.s

kern/proc.o: kern/proc.c.o

.PHONY : kern/proc.o

# target to build an object file
kern/proc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/proc.c.o
.PHONY : kern/proc.c.o

kern/proc.i: kern/proc.c.i

.PHONY : kern/proc.i

# target to preprocess a source file
kern/proc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/proc.c.i
.PHONY : kern/proc.c.i

kern/proc.s: kern/proc.c.s

.PHONY : kern/proc.s

# target to generate assembly for a file
kern/proc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/proc.c.s
.PHONY : kern/proc.c.s

kern/sched.o: kern/sched.c.o

.PHONY : kern/sched.o

# target to build an object file
kern/sched.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sched.c.o
.PHONY : kern/sched.c.o

kern/sched.i: kern/sched.c.i

.PHONY : kern/sched.i

# target to preprocess a source file
kern/sched.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sched.c.i
.PHONY : kern/sched.c.i

kern/sched.s: kern/sched.c.s

.PHONY : kern/sched.s

# target to generate assembly for a file
kern/sched.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sched.c.s
.PHONY : kern/sched.c.s

kern/sched_rr.o: kern/sched_rr.c.o

.PHONY : kern/sched_rr.o

# target to build an object file
kern/sched_rr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sched_rr.c.o
.PHONY : kern/sched_rr.c.o

kern/sched_rr.i: kern/sched_rr.c.i

.PHONY : kern/sched_rr.i

# target to preprocess a source file
kern/sched_rr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sched_rr.c.i
.PHONY : kern/sched_rr.c.i

kern/sched_rr.s: kern/sched_rr.c.s

.PHONY : kern/sched_rr.s

# target to generate assembly for a file
kern/sched_rr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sched_rr.c.s
.PHONY : kern/sched_rr.c.s

kern/sys.o: kern/sys.c.o

.PHONY : kern/sys.o

# target to build an object file
kern/sys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sys.c.o
.PHONY : kern/sys.c.o

kern/sys.i: kern/sys.c.i

.PHONY : kern/sys.i

# target to preprocess a source file
kern/sys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sys.c.i
.PHONY : kern/sys.c.i

kern/sys.s: kern/sys.c.s

.PHONY : kern/sys.s

# target to generate assembly for a file
kern/sys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/sys.c.s
.PHONY : kern/sys.c.s

kern/time.o: kern/time.c.o

.PHONY : kern/time.o

# target to build an object file
kern/time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/time.c.o
.PHONY : kern/time.c.o

kern/time.i: kern/time.c.i

.PHONY : kern/time.i

# target to preprocess a source file
kern/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/time.c.i
.PHONY : kern/time.c.i

kern/time.s: kern/time.c.s

.PHONY : kern/time.s

# target to generate assembly for a file
kern/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/time.c.s
.PHONY : kern/time.c.s

kern/util.o: kern/util.c.o

.PHONY : kern/util.o

# target to build an object file
kern/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/util.c.o
.PHONY : kern/util.c.o

kern/util.i: kern/util.c.i

.PHONY : kern/util.i

# target to preprocess a source file
kern/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/util.c.i
.PHONY : kern/util.c.i

kern/util.s: kern/util.c.s

.PHONY : kern/util.s

# target to generate assembly for a file
kern/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/kern/util.c.s
.PHONY : kern/util.c.s

lib/crt/crt.o: lib/crt/crt.c.o

.PHONY : lib/crt/crt.o

# target to build an object file
lib/crt/crt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/crt/crt.c.o
.PHONY : lib/crt/crt.c.o

lib/crt/crt.i: lib/crt/crt.c.i

.PHONY : lib/crt/crt.i

# target to preprocess a source file
lib/crt/crt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/crt/crt.c.i
.PHONY : lib/crt/crt.c.i

lib/crt/crt.s: lib/crt/crt.c.s

.PHONY : lib/crt/crt.s

# target to generate assembly for a file
lib/crt/crt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/crt/crt.c.s
.PHONY : lib/crt/crt.c.s

lib/libelf/elf.o: lib/libelf/elf.c.o

.PHONY : lib/libelf/elf.o

# target to build an object file
lib/libelf/elf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/libelf/elf.c.o
.PHONY : lib/libelf/elf.c.o

lib/libelf/elf.i: lib/libelf/elf.c.i

.PHONY : lib/libelf/elf.i

# target to preprocess a source file
lib/libelf/elf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/libelf/elf.c.i
.PHONY : lib/libelf/elf.c.i

lib/libelf/elf.s: lib/libelf/elf.c.s

.PHONY : lib/libelf/elf.s

# target to generate assembly for a file
lib/libelf/elf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/libelf/elf.c.s
.PHONY : lib/libelf/elf.c.s

lib/stdlib/stdlib.o: lib/stdlib/stdlib.c.o

.PHONY : lib/stdlib/stdlib.o

# target to build an object file
lib/stdlib/stdlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/stdlib/stdlib.c.o
.PHONY : lib/stdlib/stdlib.c.o

lib/stdlib/stdlib.i: lib/stdlib/stdlib.c.i

.PHONY : lib/stdlib/stdlib.i

# target to preprocess a source file
lib/stdlib/stdlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/stdlib/stdlib.c.i
.PHONY : lib/stdlib/stdlib.c.i

lib/stdlib/stdlib.s: lib/stdlib/stdlib.c.s

.PHONY : lib/stdlib/stdlib.s

# target to generate assembly for a file
lib/stdlib/stdlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os.elf.dir/build.make CMakeFiles/os.elf.dir/lib/stdlib/stdlib.c.s
.PHONY : lib/stdlib/stdlib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mman.elf"
	@echo "... os.elf"
	@echo "... arch/i686/boot/boot.o"
	@echo "... arch/i686/boot/gdt.o"
	@echo "... arch/i686/boot/gdt.i"
	@echo "... arch/i686/boot/gdt.s"
	@echo "... arch/i686/boot/interrupt.o"
	@echo "... arch/i686/boot/load_tables.o"
	@echo "... arch/i686/boot/multiboot.o"
	@echo "... arch/i686/drivers/pic.o"
	@echo "... arch/i686/drivers/pic.i"
	@echo "... arch/i686/drivers/pic.s"
	@echo "... arch/i686/drivers/timer.o"
	@echo "... arch/i686/drivers/timer.i"
	@echo "... arch/i686/drivers/timer.s"
	@echo "... arch/i686/drivers/vga.o"
	@echo "... arch/i686/drivers/vga.i"
	@echo "... arch/i686/drivers/vga.s"
	@echo "... arch/i686/early.o"
	@echo "... arch/i686/early.i"
	@echo "... arch/i686/early.s"
	@echo "... arch/i686/idt.o"
	@echo "... arch/i686/idt.i"
	@echo "... arch/i686/idt.s"
	@echo "... arch/i686/init.o"
	@echo "... arch/i686/init.i"
	@echo "... arch/i686/init.s"
	@echo "... arch/i686/interrupt.o"
	@echo "... arch/i686/interrupt.i"
	@echo "... arch/i686/interrupt.s"
	@echo "... arch/i686/panic.o"
	@echo "... arch/i686/panic.i"
	@echo "... arch/i686/panic.s"
	@echo "... arch/i686/sysenter.o"
	@echo "... arch/i686/thread.o"
	@echo "... arch/i686/thread.i"
	@echo "... arch/i686/thread.s"
	@echo "... arch/i686/thread_asm.o"
	@echo "... arch/i686/trace.o"
	@echo "... arch/i686/util.o"
	@echo "... arch/i686/util.i"
	@echo "... arch/i686/util.s"
	@echo "... kern/kmalloc.o"
	@echo "... kern/kmalloc.i"
	@echo "... kern/kmalloc.s"
	@echo "... kern/kmem.o"
	@echo "... kern/kmem.i"
	@echo "... kern/kmem.s"
	@echo "... kern/kprint.o"
	@echo "... kern/kprint.i"
	@echo "... kern/kprint.s"
	@echo "... kern/main.o"
	@echo "... kern/main.i"
	@echo "... kern/main.s"
	@echo "... kern/panic.o"
	@echo "... kern/panic.i"
	@echo "... kern/panic.s"
	@echo "... kern/proc.o"
	@echo "... kern/proc.i"
	@echo "... kern/proc.s"
	@echo "... kern/sched.o"
	@echo "... kern/sched.i"
	@echo "... kern/sched.s"
	@echo "... kern/sched_rr.o"
	@echo "... kern/sched_rr.i"
	@echo "... kern/sched_rr.s"
	@echo "... kern/sys.o"
	@echo "... kern/sys.i"
	@echo "... kern/sys.s"
	@echo "... kern/time.o"
	@echo "... kern/time.i"
	@echo "... kern/time.s"
	@echo "... kern/util.o"
	@echo "... kern/util.i"
	@echo "... kern/util.s"
	@echo "... lib/crt/crt.o"
	@echo "... lib/crt/crt.i"
	@echo "... lib/crt/crt.s"
	@echo "... lib/libelf/elf.o"
	@echo "... lib/libelf/elf.i"
	@echo "... lib/libelf/elf.s"
	@echo "... lib/stdlib/stdlib.o"
	@echo "... lib/stdlib/stdlib.i"
	@echo "... lib/stdlib/stdlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

